# CD ROOT Stage 
parameters:
- name: envId
  type: string
- name: devOpsAgentPool
  type: string
- name: devOpsAgentImage
  type: string
- name: applicationName
  type: string
- name: msixVersion
  type: string
- name: msixImageFileName
  type: string
- name: msixAppAttachUNCServer
  type: string
- name: msixAppAttachShareName
  type: string
- name: msixAzureVMLocalPath
  type: string
- name: azureSubscription
  type: string
- name: resourceGroup
  type: string
- name: storageAccount
  type: string
- name: hostPoolName
  type: string
- name: UserName
  type: string
- name: UserPassword
  type: string

stages:
- stage: CD
  displayName: CD
  jobs:
  - deployment: PublishImage
    displayName: PublishImage
    pool: ${{parameters.devOpsAgentPool}}
      vmImage: ${{parameters.devOpsAgentImage}}
    environment: ${{parameters.envId}}
    strategy:
      runOnce:
        deploy:
          steps:
          # Image (VHDX) publishing process
          - template: ./CD-imagePublish-steps.yaml
            parameters:
              azureSubscription: ${{ parameters.azureSubscription}}
              resourceGroup: ${{ parameters.resourceGroup }}
              storageAccount: ${{ parameters.storageAccount }}
              applicationName: ${{ parameters.applicationName}}
              msixVersion: ${{ parameters.msixVersion }}
              msixAzureVMLocalPath: ${{ parameters.msixAzureVMLocalPath}}
              msixImageFileName: ${{ parameters.msixImageFileName }}
              msixAppAttachUNCServer: ${{ parameters.msixAppAttachUNCServer }}
              msixAppAttachShareName: ${{ parameters.msixAppAttachShareName }}
              UserName: ${{ parameters.UserName }}
              UserPassword: ${{ parameters.UserPassword }}
  
          # App (AVD MSIX Appattach) publishing process
          # Output the variable 'msixPackageFullName'
          - template: ./CD-appPublish-steps.yaml
            parameters:
              azureSubscription: ${{ parameters.azureSubscription }}
              resourceGroup: ${{ parameters.resourceGroup }}
              hostPoolName: ${{ parameters.hostPoolName }}
              msixVersion: ${{ parameters.msixVersion }}
              msixApplicationUNCPath: '\\${{ parameters.msixAppAttachUNCServer }}\${{ parameters.msixAppAttachShareName }}'
              msixImageFileName: ${{ parameters.msixImageFileName }}
              applicationName: ${{ parameters.applicationName}}
              
  # Manual intervention Job for Release evaluation
  - job: waitForValidation
    displayName: Wait for external validation
    dependsOn: PublishImage
    pool: server
    timeoutInMinutes: 4320 # job times out in 3 days
    steps:
    - task: ManualValidation@0
      timeoutInMinutes: 1440 # task times out in 1 day
      inputs:
        # If you want to notify users for the gate is optional. NotifyUsers defines the list of users that will be notified that the task has been activated.
        # notifyUsers: general@contoso.com
        instructions: 'MSIX package has been registered and currently inactive. Make sure after the first activation that this package exists in any application group to make it available to end-users.'
        onTimeout: 'resume'

  - job: activateMsixPackage
    displayName: Activate MSIX Package
    condition: and(eq(dependencies.PublishImage.result, 'Succeeded'),in(dependencies.waitForValidation.result, 'Succeeded', 'Skipped'))
    dependsOn: ['PublishImage', 'waitForValidation']
    pool:
      vmImage: windows-latest
    variables:
      msixPackageFullName: $[ dependencies.PublishImage.outputs['PublishImage.createMsixPackage.msixPackageFullName'] ]
    steps:

    - template: ./CD-appAVDApprovalActive-steps.yaml
      parameters:
        azureSubscription: ${{ parameters.azureSubscription }}
        resourceGroup: ${{ parameters.resourceGroup }}
        hostPoolName: ${{ parameters.hostPoolName }}
        applicationFullName: $(msixPackageFullName)
        applicationName: ${{ parameters.applicationName}}
