# CD ROOT Stage 
parameters:
- name: envId
  type: string
- name: applicationName
  type: string
- name: msixVersion
  type: string
- name: msixImageFileName
  type: string
- name: msixAppAttachUNCServer
  type: string
- name: msixAppAttachShareName
  type: string
- name: msixAzureVMLocalPath
  type: string

stages:
- stage: CD
  displayName: CD
  jobs:
  - deployment: PublishImage
    displayName: PublishImage
    pool: # <name of an agent pool for Self-hosted agents>
      vmImage: windows-latest
    environment: ${{parameters.envId}}
    strategy:
      runOnce:
        deploy:
          steps:
          # Image (VHDX) publishing process
          - template: ./CD-imagePublish-steps.yaml
            parameters:
              azureSubscription: $(azureSubscription)
              resourceGroup: $(resourceGroup)
              storageAccount: $(storageAccount)
              applicationName: ${{ parameters.applicationName}}
              msixVersion: ${{ parameters.msixVersion }}
              msixAzureVMLocalPath: ${{ parameters.msixAzureVMLocalPath}}
              msixImageFileName: ${{ parameters.msixImageFileName }}
              msixAppAttachUNCServer: ${{ parameters.msixAppAttachUNCServer }}
              msixAppAttachShareName: ${{ parameters.msixAppAttachShareName }}

          # App (AVD MSIX Appattach) publishing process
          # Output the variable 'msixPackageFullName'
          - template: ./CD-appPublish-steps.yaml
            parameters:
              azureSubscription: $(azureSubscription)
              resourceGroup: $(resourceGroup)
              hostPoolName: $(hostPoolName)
              msixVersion: ${{ parameters.msixVersion }}
              msixApplicationUNCPath: '\\${{ parameters.msixAppAttachUNCServer }}\${{ parameters.msixAppAttachShareName }}'
              msixImageFileName: ${{ parameters.msixImageFileName }}
              applicationName: ${{ parameters.applicationName}}
              
  # Manual intervention Job for Release evaluation
  - job: waitForValidation
    displayName: Wait for external validation
    dependsOn: PublishImage
    pool: server
    timeoutInMinutes: 4320 # job times out in 3 days
    steps:
    - task: ManualValidation@0
      timeoutInMinutes: 1440 # task times out in 1 day
      inputs:
        notifyUsers: $(notifyManualValidationEmails)
        instructions: 'MSIX package has been registered and currently inactive. Make sure this package exists in any application group so it can be activated and made available to end-users.'
        onTimeout: 'resume'

  - job: activateMsixPackage
    displayName: Activate MSIX Package
    condition: and(eq(dependencies.PublishImage.result, 'Succeeded'),in(dependencies.waitForValidation.result, 'Succeeded', 'Skipped'))
    dependsOn: ['PublishImage', 'waitForValidation']
    pool:
      vmImage: windows-latest
    variables:
      msixPackageFullName: $[ dependencies.PublishImage.outputs['PublishImage.createMsixPackage.msixPackageFullName'] ]
    steps:

    - template: ./CD-appAVDApprovalActive-steps.yaml
      parameters:
        azureSubscription: $(azureSubscription)
        resourceGroup: $(resourceGroup)
        hostPoolName: $(hostPoolName)
        applicationFullName: $(msixPackageFullName)
        applicationName: ${{ parameters.applicationName}}
