# Config File
parameters:
- name: fileLocation
  type: string
- name: fileName
  type: string
- name: psfEnabled
  type: string

steps:
- script: |
    curl -o ${{parameters.fileName}} ${{parameters.fileLocation}}/${{parameters.fileName}}
  displayName: DOWNLOAD App zip package

- task: ExtractFiles@1
  displayName: EXPAND App zip package AppConfigured
  inputs: 
    archiveFilePatterns: ${{parameters.fileName}}
    destinationFolder: AppConfigured
    cleanDestinationFolder: false 

- task: CopyFiles@2
  displayName: COPY Msix artifacts
  inputs:
    sourceFolder: msix-appattach/msix_application_artifacts
    targetFolder: AppConfigured
    flattenFolders: false

- task: CopyFiles@2
  displayName: COPY Psf artifacts
  condition: eq('${{ parameters.psfEnabled }}', 'enabled')
  inputs:
    sourceFolder: msix-appattach/psf_application_artifacts
    targetFolder: AppConfigured
    flattenFolders: false
    overWrite: true

# Add tasks here if you need to change the App binaries like adding an SDK
# Target folder would be "AppConfigured" as root