# CI ROOT Stage
parameters:
- name: fileLocation
  type: string
- name: fileName
  type: string
- name: applicationName
  type: string
- name: msixVersion
  type: string
- name: msixImageSize
  type: string
- name: msixApplicationUNCPath
  type: string

stages:
- stage: CI
  displayName: CI

  jobs:

  - job: CreateImage
    displayName: CreateImage
    pool:
      vmImage: windows-latest
    steps:
    # Application configuration process
    - template: ./CI-appConfig-steps.yaml
      parameters:
        fileLocation: ${{ parameters.fileLocation }}
        fileName: ${{ parameters.fileName }}
        msixVersion: ${{ parameters.msixVersion }}
        publisher: $(publisher)
        publisherDisplayName: $(publisherDisplayName)
        applicationName: ${{ parameters.applicationName }}
        applicationDisplayName: $(applicationDisplayName)
        applicationDescription: $(applicationDescription)
        applicationExecutable: $(applicationExecutable)

    # MSIX configuration process
    - template: ./CI-msixConfig-steps.yaml

    # MSIX packaging process
    - template: ./CI-msixPackaging-steps.yaml
      parameters:
        CertificateName: $(CertificateName)
        CertificatePasswordVariable: $(CertificatePasswordVariable) # From variable group
        imageMetadataFile: src/image_metadata.xml
        msixVersion: ${{ parameters.msixVersion }}
        msixApplicationUNCPath: ${{ parameters.msixApplicationUNCPath }}\${{ parameters.applicationName}}-msix-image-${{ parameters.msixVersion }}.vhdx
        msixImageSize: ${{ parameters.msixImageSize }}
        applicationName: ${{ parameters.applicationName}}