# CI ROOT Stage
parameters:
- name: fileLocation
  type: string
- name: fileName
  type: string
- name: applicationName
  type: string
- name: applicationExecutable
  type: string
- name: msixVersion
  type: string
- name: msixImageSize
  type: string
- name: msixApplicationUNCPath
  type: string
- name: msixImageFileName
  type: string
- name: applicationDisplayName
  type: string
- name: applicationDescription
  type: string
- name: publisher
  type: string
- name: publisherDisplayName
  type: string
- name: psfExecutable
  type: string
- name: CertificateName
  type: string
- name: CertificatePasswordVariable
  type: string
- name: psfEnabled
  type: boolean

stages:
- stage: CI
  displayName: CI

  jobs:

  - job: CreateImage
    displayName: CreateImage
    pool:
      vmImage: windows-latest
    steps:
    # Application configuration process
    - template: ./CI-appConfig-steps.yaml
      parameters:
        fileLocation: ${{ parameters.fileLocation }}
        fileName: ${{ parameters.fileName }}
        psfEnabled: ${{ parameters.psfEnabled }}

    # MSIX configuration process
    - template: ./CI-msixConfig-steps.yaml
      parameters:
        applicationName: ${{ parameters.applicationName}}
        applicationExecutable: ${{ parameters.applicationExecutable}}
        applicationDisplayName: ${{ parameters.applicationDisplayName }}
        applicationDescription: ${{ parameters.applicationDescription }}
        msixVersion: ${{ parameters.msixVersion }}
        publisher: ${{ parameters.publisher }}
        publisherDisplayName: ${{ parameters.publisherDisplayName }}
        psfEnabled: ${{ parameters.psfEnabled }}
        psfExecutable: ${{ parameters.psfExecutable }}

    # MSIX packaging process
    - template: ./CI-msixPackaging-steps.yaml
      parameters:
        CertificateName: ${{ parameters.CertificateName }}
        CertificatePasswordVariable: ${{ parameters.CertificatePasswordVariable }}
        imageMetadataFile: msix-appattach/image_metadata.xml
        msixVersion: ${{ parameters.msixVersion }}
        msixApplicationUNCPath: ${{ parameters.msixApplicationUNCPath }}
        msixImageFileName: ${{ parameters.msixImageFileName }}
        msixImageSize: ${{ parameters.msixImageSize }}
        applicationName: ${{ parameters.applicationName}}
