# CI ROOT Stage
parameters:
- name: fileLocation
  type: string
- name: fileName
  type: string
- name: applicationName
  type: string
- name: applicationExecutable
  type: string
- name: msixVersion
  type: string
- name: msixImageSize
  type: string
- name: msixApplicationUNCPath
  type: string
- name: msixImageFileName
  type: string
- name: applicationDisplayName
  type: string
- name: applicationDescription
  type: string
- name: publisher
  type: string
- name: publisherDisplayName
  type: string
- name: psfExecutable
  type: string
- name: CertificateName
  type: string
- name: CertificatePasswordVariable
  type: string
- name: psfEnabled
  type: boolean

stages:
- stage: CI
  displayName: CI

  jobs:

  - job: CreateImage
    displayName: CreateImage
    pool:
      vmImage: windows-latest
    steps:
    # Application configuration process
    - template: ./CI-appConfig-steps.yaml
      parameters:
      - name: fileLocation
        type: string
        default: ${{ parameters.fileLocation }}
      - name: fileName
        type: string
        default: ${{ parameters.fileName }}
      - name: psfEnabled 
        type: boolean 
        default: ${{ parameters.psfEnabled }}


    # MSIX configuration process
    - template: ./CI-msixConfig-steps.yaml
      parameters:
      - name: applicationName
        type: string
        default: ${{ parameters.applicationName}}
      - name: applicationExecutable
        type: string
        default: ${{ parameters.applicationExecutable}}
      - name: applicationDisplayName
        type: string
        default: ${{ parameters.applicationDisplayName }}
      - name: applicationDescription
        type: string
        default: ${{ parameters.applicationDescription }}
      - name: msixVersion
        type: string
        default: ${{ parameters.msixVersion }}
      - name: publisher
        type: string
        default: ${{ parameters.publisher }}
      - name: publisherDisplayName
        type: string
        default: ${{ parameters.publisherDisplayName }}
      - name: psfExecutable
        type: string
        default: ${{ parameters.psfExecutable }}
      - name: psfEnabled 
        type: boolean 
        default: ${{ parameters.psfEnabled }}

    # MSIX packaging process
    - template: ./CI-msixPackaging-steps.yaml
      parameters:
        CertificateName: ${{ parameters.CertificateName }}
        CertificatePasswordVariable: ${{ parameters.CertificatePasswordVariable }}
        imageMetadataFile: msix-appattach/image_metadata.xml
        msixVersion: ${{ parameters.msixVersion }}
        msixApplicationUNCPath: ${{ parameters.msixApplicationUNCPath }}
        msixImageFileName: ${{ parameters.msixImageFileName }}
        msixImageSize: ${{ parameters.msixImageSize }}
        applicationName: ${{ parameters.applicationName}}
